spring:
    application:
        name: online-bookstore

    jackson:
        default-property-inclusion: non_null

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        operationsSorter: method
        tagsSorter: alpha

swagger:
    dev-url: http://localhost:8080
    prod-url: https://api.onlinebookstore.com
